runtime: go111
service: default

handlers:
  - url: /.*
    script: auto

instance_class: F1
automatic_scaling:
  max_concurrent_requests: 80
  max_instances: 3
  min_instances: 0
  min_idle_instances: 0

