version: '2'

services:
  appsearch:
    image: docker.elastic.co/app-search/app-search:7.5.1
    environment:
      - "elasticsearch.host=http://elasticsearch:9200"
      - "allow_es_settings_modification=true"
      - "JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 3002:3002
    networks:
      - elastic

networks:
  elastic: