CREATE TABLE User (
    ID STRING(256) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    Email STRING(1024) NOT NULL,
    ModifiedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
    Password STRING(256) NOT NULL,
    UserID STRING(MAX) NOT NULL,
) PRIMARY KEY (ID)

CREATE TABLE Tweet (
	ID STRING(256) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,
	ModifiedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
	Text STRING(1024) NOT NULL,
	UserID STRING(256) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User (ID)
) PRIMARY KEY (ID)

CREATE TABLE Likes (
	ID STRING(256) NOT NULL,
	Count INT64 NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,
	ModifiedAt TIMESTAMP NOT NULL,
	TweetID STRING(256) NOT NULL,
	UserID STRING(256) NOT NULL,
	FOREIGN KEY (TweetID) REFERENCES Tweet(ID),
) PRIMARY KEY (ID),
INTERLEAVE IN PARENT Tweet ON DELETE CASCADE;

ALTER TABLE Likes ADD FOREIGN KEY (UserID) REFERENCES User(UserID)