// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"

	"github.com/chidakiyo/benkyo/go-db-ent-atlas/ent/migrate"

	"github.com/chidakiyo/benkyo/go-db-ent-atlas/ent/car"
	"github.com/chidakiyo/benkyo/go-db-ent-atlas/ent/foo"
	"github.com/chidakiyo/benkyo/go-db-ent-atlas/ent/hoge"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Car is the client for interacting with the Car builders.
	Car *CarClient
	// Foo is the client for interacting with the Foo builders.
	Foo *FooClient
	// Hoge is the client for interacting with the Hoge builders.
	Hoge *HogeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Car = NewCarClient(c.config)
	c.Foo = NewFooClient(c.config)
	c.Hoge = NewHogeClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Car:    NewCarClient(cfg),
		Foo:    NewFooClient(cfg),
		Hoge:   NewHogeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Car:    NewCarClient(cfg),
		Foo:    NewFooClient(cfg),
		Hoge:   NewHogeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Car.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Car.Use(hooks...)
	c.Foo.Use(hooks...)
	c.Hoge.Use(hooks...)
}

// CarClient is a client for the Car schema.
type CarClient struct {
	config
}

// NewCarClient returns a client for the Car from the given config.
func NewCarClient(c config) *CarClient {
	return &CarClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `car.Hooks(f(g(h())))`.
func (c *CarClient) Use(hooks ...Hook) {
	c.hooks.Car = append(c.hooks.Car, hooks...)
}

// Create returns a builder for creating a Car entity.
func (c *CarClient) Create() *CarCreate {
	mutation := newCarMutation(c.config, OpCreate)
	return &CarCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Car entities.
func (c *CarClient) CreateBulk(builders ...*CarCreate) *CarCreateBulk {
	return &CarCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Car.
func (c *CarClient) Update() *CarUpdate {
	mutation := newCarMutation(c.config, OpUpdate)
	return &CarUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CarClient) UpdateOne(ca *Car) *CarUpdateOne {
	mutation := newCarMutation(c.config, OpUpdateOne, withCar(ca))
	return &CarUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CarClient) UpdateOneID(id int) *CarUpdateOne {
	mutation := newCarMutation(c.config, OpUpdateOne, withCarID(id))
	return &CarUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Car.
func (c *CarClient) Delete() *CarDelete {
	mutation := newCarMutation(c.config, OpDelete)
	return &CarDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CarClient) DeleteOne(ca *Car) *CarDeleteOne {
	return c.DeleteOneID(ca.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *CarClient) DeleteOneID(id int) *CarDeleteOne {
	builder := c.Delete().Where(car.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CarDeleteOne{builder}
}

// Query returns a query builder for Car.
func (c *CarClient) Query() *CarQuery {
	return &CarQuery{
		config: c.config,
	}
}

// Get returns a Car entity by its id.
func (c *CarClient) Get(ctx context.Context, id int) (*Car, error) {
	return c.Query().Where(car.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CarClient) GetX(ctx context.Context, id int) *Car {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CarClient) Hooks() []Hook {
	return c.hooks.Car
}

// FooClient is a client for the Foo schema.
type FooClient struct {
	config
}

// NewFooClient returns a client for the Foo from the given config.
func NewFooClient(c config) *FooClient {
	return &FooClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `foo.Hooks(f(g(h())))`.
func (c *FooClient) Use(hooks ...Hook) {
	c.hooks.Foo = append(c.hooks.Foo, hooks...)
}

// Create returns a builder for creating a Foo entity.
func (c *FooClient) Create() *FooCreate {
	mutation := newFooMutation(c.config, OpCreate)
	return &FooCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Foo entities.
func (c *FooClient) CreateBulk(builders ...*FooCreate) *FooCreateBulk {
	return &FooCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Foo.
func (c *FooClient) Update() *FooUpdate {
	mutation := newFooMutation(c.config, OpUpdate)
	return &FooUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FooClient) UpdateOne(f *Foo) *FooUpdateOne {
	mutation := newFooMutation(c.config, OpUpdateOne, withFoo(f))
	return &FooUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FooClient) UpdateOneID(id int) *FooUpdateOne {
	mutation := newFooMutation(c.config, OpUpdateOne, withFooID(id))
	return &FooUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Foo.
func (c *FooClient) Delete() *FooDelete {
	mutation := newFooMutation(c.config, OpDelete)
	return &FooDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FooClient) DeleteOne(f *Foo) *FooDeleteOne {
	return c.DeleteOneID(f.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *FooClient) DeleteOneID(id int) *FooDeleteOne {
	builder := c.Delete().Where(foo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FooDeleteOne{builder}
}

// Query returns a query builder for Foo.
func (c *FooClient) Query() *FooQuery {
	return &FooQuery{
		config: c.config,
	}
}

// Get returns a Foo entity by its id.
func (c *FooClient) Get(ctx context.Context, id int) (*Foo, error) {
	return c.Query().Where(foo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FooClient) GetX(ctx context.Context, id int) *Foo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FooClient) Hooks() []Hook {
	return c.hooks.Foo
}

// HogeClient is a client for the Hoge schema.
type HogeClient struct {
	config
}

// NewHogeClient returns a client for the Hoge from the given config.
func NewHogeClient(c config) *HogeClient {
	return &HogeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `hoge.Hooks(f(g(h())))`.
func (c *HogeClient) Use(hooks ...Hook) {
	c.hooks.Hoge = append(c.hooks.Hoge, hooks...)
}

// Create returns a builder for creating a Hoge entity.
func (c *HogeClient) Create() *HogeCreate {
	mutation := newHogeMutation(c.config, OpCreate)
	return &HogeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Hoge entities.
func (c *HogeClient) CreateBulk(builders ...*HogeCreate) *HogeCreateBulk {
	return &HogeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Hoge.
func (c *HogeClient) Update() *HogeUpdate {
	mutation := newHogeMutation(c.config, OpUpdate)
	return &HogeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HogeClient) UpdateOne(h *Hoge) *HogeUpdateOne {
	mutation := newHogeMutation(c.config, OpUpdateOne, withHoge(h))
	return &HogeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HogeClient) UpdateOneID(id string) *HogeUpdateOne {
	mutation := newHogeMutation(c.config, OpUpdateOne, withHogeID(id))
	return &HogeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Hoge.
func (c *HogeClient) Delete() *HogeDelete {
	mutation := newHogeMutation(c.config, OpDelete)
	return &HogeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *HogeClient) DeleteOne(h *Hoge) *HogeDeleteOne {
	return c.DeleteOneID(h.ID)
}

// DeleteOne returns a builder for deleting the given entity by its id.
func (c *HogeClient) DeleteOneID(id string) *HogeDeleteOne {
	builder := c.Delete().Where(hoge.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HogeDeleteOne{builder}
}

// Query returns a query builder for Hoge.
func (c *HogeClient) Query() *HogeQuery {
	return &HogeQuery{
		config: c.config,
	}
}

// Get returns a Hoge entity by its id.
func (c *HogeClient) Get(ctx context.Context, id string) (*Hoge, error) {
	return c.Query().Where(hoge.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HogeClient) GetX(ctx context.Context, id string) *Hoge {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HogeClient) Hooks() []Hook {
	return c.hooks.Hoge
}
