// Code generated by ent, DO NOT EDIT.

package foo

const (
	// Label holds the string label denoting the foo type in the database.
	Label = "foo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFooFoo holds the string denoting the foo_foo field in the database.
	FieldFooFoo = "foo_foo"
	// Table holds the table name of the foo in the database.
	Table = "foos"
)

// Columns holds all SQL columns for foo fields.
var Columns = []string{
	FieldID,
	FieldFooFoo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
