// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// Foo is the predicate function for foo builders.
type Foo func(*sql.Selector)

// Hoge is the predicate function for hoge builders.
type Hoge func(*sql.Selector)
