steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--max-instances'
      - '1'
      - '--vpc-connector'
      - 'projects/${_VPC_PROJECT}/locations/${_REGION}/connectors/${_CONNECTOR}'
      - '--set-env-vars'
      - "GCP_PROJECT=${PROJECT_ID}"

substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: run-redis
  _CONNECTOR: _ # FIXME
  _VPC_PROJECT: _ # FIXME

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}